replicaCount: 1
apiService:
  group: admission.anchore.io
  version: v1beta1
image:
  repository: viglesiasce/anchore-image-admission-server
  tag: latest
  pullPolicy: Always
service:
  name: anchoreimagecheck
  type: ClusterIP
  externalPort: 443
  internalPort: 443
anchore-engine:
  enabled: true
  users:
    admin:
      password: image-validator
resources: {}